name: DataScience API Workflow

on:
  push:
    branches:
      - datascience
  pull_request:
    branches:
      - datascience

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI App (test only)
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 --reload &
          sleep 5
          curl http://127.0.0.1:8000/docs

      - name: Run tests
        run: pytest
